name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --output=./TestGitActions/bin --configuration Release --no-restore
    - name: Build
      run: dotnet publish --output=./TestGitActions/bin
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        path: ./TestGitActions/bin/
